#!/bin/sh

urlGitRepo=$1 # First parameter Url to Git Repo Submodule
name=$2


echo "Remember. For newer versions use Relative Paths/URL"

if [ ! -z "$urlGitRepo" ] && [ ! -z "$name" ] # checking if the commit message is present. If not then aborting.
then
  git submodule add $urlGitRepo $name
  git submodule init
else
  echo "$urlGitRepo"
fi
